SELECT DISTINCT
    PCEST.CODPROD,
    PCPRODUT.DESCRICAO,
    PCFORNEC.FORNECEDOR
FROM
    PCEST
INNER JOIN
    PCPRODUT ON PCEST.CODPROD = PCPRODUT.CODPROD
INNER JOIN
    PCFORNEC ON PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
WHERE
    PCFORNEC.FORNECEDOR LIKE 'INTELBRAS%'